### ISSUE TITLE
Can we create new multiple line for title of notification?

### ISSUE THREAD

**Issue by kvu-luong** [ScaleDrone/html5-javascript-push-notifications#3]
I try to use \n and <br/> to make new line for title of notification but it only work for body of notification. Is there any way to make it work for title.
Thank in advance!

**Comment by herkyl** [comment]
I'm unsure if this is possible. It's quite likely that multi line headers might not be a thing. Either way it's best to direct this to the HTML5 notifications page: https://developer.mozilla.org/en-US/docs/Web/API/notification

**Comment by kvu-luong** [comment]
Thank you for spending time to answer my issue!

Vào Th 4, 15 thg 4, 2020 lúc 22:44 Serge <notifications@github.com> đã viết:
